spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.5:3306/employees?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&verifyServerCertificate=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: '{cipher}AQA6Gxs5YL6pGCPchGAMi8bXDtTxKz79iRJRlp3NIhp2amm+BCP8ITdhl85BCQw/oU2ApJEuaGb/rQziIMS1HFObVv/T7ES5r/QZ8xvyKhLQMQEGcFejcdVIlX5BgpdVizv+LC9W5U+162qB0czVgEKyrkBk44iLjAw+VGh4Vk4HSPXgEzzcBqqr1LVZicGvnetC6zlYRpafRgi5Og1OzwvrbMSaV1xZWuvZLJJbUJmTV/K+5TnOQvq38UZXVMpx243iE2sUAqa77CVCg+SzIqVUIIp6OzN5SEm+XSHfBFa+xhsOjoDL/knu5d4sa+sSbEIb6pQxIeMHiia6q74K8BQppuKKh033Iwob0x4vU/Jz7k8dODEuayGDeHFXdiq7ElQ='
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: true
      write_dates_as_timestamps: false