spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.5:3306/employees?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&verifyServerCertificate=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: '{cipher}AQBGgFMZZJegAkaMDtkwIFcWWd2r+wfDk14Cb/BLa21/R3hSTSndnuhJhCo6dNs9S3xc8g3BTAeePzBS98r0QyYCGTtaseVs9peRh8TzALerYNui3ypClqqmstn4wyOLZdwf2poAhUuCD3t9ObanbfpQvcXB9468qTMcjROnCdsKyIxU3THiziI/FPiOyrJrd3xrnEYAnwkJ4YfaqAYT8gSjdA0Q/R1arY0w2uGCbeLcrcgZejy8Ujwq4joWScmWEyM8VHvkTA0dmkAiYCCHw5Hi9bMy4keAQiK1l5ld7th5UjzG5j8ITyuBqykRFj8xm96k6fUaRlsydv5S3lOUSFUSdRtOo0fhWFEfq4pKXonvUhtBvimF75ErZJpHpWiXLc4='
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
