spring:
  profiles: dev
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/bus/**
          filters:
            - StripPrefix=1
          uri: lb://bus-app

---
spring:
  profiles: beta
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/bus/**
          filters:
            - StripPrefix=1
          uri: lb://bus-app